# Generated by Django 4.0.3 on 2022-05-28 11:15

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('metkeyword', models.CharField(max_length=200, null=True)),
                ('header_image', models.ImageField(upload_to='headerimage')),
                ('upload_fonts', models.FileField(null=True, upload_to='media')),
                ('short_discription', models.CharField(max_length=255)),
                ('long_discription', froala_editor.fields.FroalaField()),
                ('character_map_img', models.ImageField(upload_to='characterimage')),
                ('publish', models.BooleanField(default=False, null=True)),
                ('Total_downloads', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
