# Generated by Django 4.0.3 on 2022-05-29 16:20

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', froala_editor.fields.FroalaField()),
                ('privacypolicy', froala_editor.fields.FroalaField()),
                ('termsandcondition', froala_editor.fields.FroalaField()),
                ('ourpages', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
