# Generated by Django 4.0.3 on 2022-05-29 17:15

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websitename', models.CharField(max_length=50)),
                ('ouremail', models.EmailField(max_length=254)),
                ('copyright', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='websiteimages')),
                ('websitediscription', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
