# Generated by Django 4.0.3 on 2022-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='favicon',
            field=models.ImageField(default='SOME STRING', upload_to=''),
        ),
    ]
