# Generated by Django 4.0.3 on 2022-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_modification_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='favicon',
            field=models.ImageField(default='AF', upload_to=''),
        ),
    ]
